display += "<div class='main-content'> ";
display += "<div class='row'> ";
display += "<div class='col-md-3 col-xs-12'> ";
display += "<img src='assets/images/rome-colosseum.jpg' alt='' longdesc='hamburg to rome'/> ";
display += "<img class='logo' src='assets/images/luftansa-logo.png' alt='luftansa' /> ";
display += "</div> ";
display += "<div class='col-md-2 col-xs-6'> ";
display += "<ul class='list-unstyled'> ";
display += "<li>LF-202</li> ";
display += "<li><span>HAM > FCO</span></li> ";
display += "<li>Depart: 10:00 AM</li> ";
display += "<li>Arrive: 1.40 PM</li> ";
display += "</ul> ";
display += "</div> ";
display += "<div class='col-md-2 col-xs-6'> ";
display += "<ul class='list-unstyled'> ";
display += "<li>LF-202</li> ";
display += "<li><span>FCO > HAM</span></li> ";
display += "<li>Depart: 5:00 PM</li> ";
display += "<li>Arrive: 8.45 PM</li> ";
display += "</ul> ";
display += "</div> ";
display += "<div class='col-md-2 price col-xs-5 text-center'> ";
display += "&euro;201.00 ";
display += "</div> ";
display += "<div class='col-md-3 col-xs-7'> ";
display += "<button class='btn btn-primary' type='submit'>Select this flight</button> ";
display += "</div> ";
display += "</div> ";
display += "</div> ";
